spring:
  application:
    name: onuldo-server

server:
  address: 0.0.0.0
  port: 8080


  profiles:
    active: local
    group:
      local: "local"
      dev: "dev"
      prod: "prod"
    include:
      - security
      - actuator
      - redis
      - aws
      - docs
      - datasource
      - fcm


logging:
  level:
    com.onuldo: INFO
    org.springframework.web: INFO
