spring:
  application:
    name: onuldo-server

  profiles:
    active: local
    group:
      local: "local"
      dev: "dev"
      prod: "prod"
    include:
      - security
      - actuator
      - redis
      - aws
      - docs
      - datasource


logging:
  level:
    com.onuldo: INFO
    org.springframework.web: INFO
